"""Tests for subspace-restricted mode search and Laplace-weighted mixtures.

Two related gaps in the multi-mode path:

* Candidates were only ever generated by a Latin hypercube over the *full*
  parameter space, so a narrow secondary mode was undiscoverable -- a GW sky
  reflection a few 0.01 rad across is ~1e-4 of the sky.  ``mode_search_subspace``
  varies only the coordinates the degeneracy lives in.
* Components were weighted equally, which ignores that a broad shallow mode
  holds more posterior mass than a narrow tall one.  ``mode_weights='laplace'``
  weights by each mode's Laplace local evidence.
"""

import numpy as np
import pytest
from bilby.core.sampler.base_sampler import SamplerError

from bilby_laplace.sampler import GaussianMixtureFlow, Laplace

MEANS = [np.array([-3.0, 0.0]), np.array([3.0, 0.0])]
TIGHT = np.diag([0.04, 0.04])
BROAD = np.diag([1.0, 1.0])


# --------------------------------------------------------------------------
# GaussianMixtureFlow weighting
# --------------------------------------------------------------------------


def test_equal_weights_by_default():
    flow = GaussianMixtureFlow(MEANS, [TIGHT, TIGHT])

    np.testing.assert_allclose(flow.weights, [0.5, 0.5])


def test_log_weights_are_normalised():
    """Unnormalised log-evidences must be accepted directly."""
    flow = GaussianMixtureFlow(MEANS, [TIGHT, TIGHT], log_weights=[1000.0, 1000.0 + np.log(3.0)])

    np.testing.assert_allclose(flow.weights, [0.25, 0.75], rtol=1e-9)


def test_log_weights_must_match_component_count():
    with pytest.raises(ValueError, match="one entry per component"):
        GaussianMixtureFlow(MEANS, [TIGHT, TIGHT], log_weights=[0.0, 0.0, 0.0])


def test_weighted_log_prob_integrates_to_one():
    """The density must stay normalised once weights are unequal."""
    flow = GaussianMixtureFlow(MEANS, [TIGHT, TIGHT], log_weights=[np.log(0.2), np.log(0.8)])
    grid = np.linspace(-8, 8, 400)
    xx, yy = np.meshgrid(grid, grid)
    pts = np.column_stack([xx.ravel(), yy.ravel()])
    cell = (grid[1] - grid[0]) ** 2

    total = np.exp(flow.log_prob(pts)).sum() * cell

    assert total == pytest.approx(1.0, abs=1e-3)


def test_log_prob_handles_single_points_and_batches():
    """Both branches must apply the weight vector.

    ``multivariate_normal.logpdf`` collapses a single-row 2-D input to a scalar,
    so the ``(K,)`` shape covers a bare point *and* a one-row batch; only a
    genuinely multi-row input reaches the ``(K, N)`` branch.
    """
    from scipy.special import logsumexp
    from scipy.stats import multivariate_normal

    log_w = np.log(np.array([0.1, 0.9]))
    flow = GaussianMixtureFlow(MEANS, [TIGHT, TIGHT], log_weights=log_w)

    def expected(point):
        per = [multivariate_normal(mean=m, cov=TIGHT).logpdf(point) for m in MEANS]
        return logsumexp(np.array(per) + log_w)

    assert float(flow.log_prob(MEANS[1])) == pytest.approx(expected(MEANS[1]))
    assert float(flow.log_prob(np.atleast_2d(MEANS[1]))) == pytest.approx(expected(MEANS[1]))

    batch = np.vstack([MEANS[0], MEANS[1], np.zeros(2)])
    out = flow.log_prob(batch)
    assert out.shape == (3,)
    for i, row in enumerate(batch):
        assert out[i] == pytest.approx(expected(row))


def test_sampling_follows_the_weights(monkeypatch):
    flow = GaussianMixtureFlow(MEANS, [TIGHT, TIGHT], log_weights=[np.log(0.2), np.log(0.8)])

    x, _ = flow.sample_and_log_prob(4000)

    assert np.mean(x[:, 0] > 0) == pytest.approx(0.8, abs=0.03)


# --------------------------------------------------------------------------
# Laplace weighting: volume, not just height
# --------------------------------------------------------------------------


def test_broad_mode_can_outweigh_a_taller_narrow_one():
    """The point of the feature.  Equal log-posterior, different widths."""
    modes = [(MEANS[0], TIGHT, 10.0), (MEANS[1], BROAD, 10.0)]

    log_w = Laplace._laplace_mode_log_weights(modes, ndim=2)

    assert log_w[1] > log_w[0]
    # det ratio is (1/0.04)^2 = 625, so the broad mode carries 25x the mass.
    assert np.exp(log_w[1] - log_w[0]) == pytest.approx(25.0, rel=1e-6)


def test_weighting_by_peak_height_alone_would_disagree():
    """A narrow mode with a higher peak still loses if it is narrow enough."""
    modes = [(MEANS[0], TIGHT, 12.0), (MEANS[1], BROAD, 10.0)]

    log_w = Laplace._laplace_mode_log_weights(modes, ndim=2)

    assert modes[0][2] > modes[1][2]  # taller peak...
    assert log_w[1] > log_w[0]  # ...but less mass


def test_laplace_weight_matches_the_analytic_evidence():
    modes = [(MEANS[0], TIGHT, 10.0)]

    log_w = Laplace._laplace_mode_log_weights(modes, ndim=2)

    expected = 10.0 + 0.5 * 2 * np.log(2 * np.pi) + 0.5 * np.log(np.linalg.det(TIGHT))
    assert log_w[0] == pytest.approx(expected)


def test_non_positive_definite_covariance_falls_back_to_log_posterior():
    modes = [(MEANS[0], np.array([[1.0, 0.0], [0.0, -1.0]]), 7.0)]

    log_w = Laplace._laplace_mode_log_weights(modes, ndim=2)

    assert log_w[0] == pytest.approx(7.0)


# --------------------------------------------------------------------------
# Stratified apportionment of the initial cloud
# --------------------------------------------------------------------------


@pytest.mark.parametrize("n", [1000, 1001, 999])
def test_counts_sum_to_n_and_follow_the_weights(n):
    counts = Laplace._stratified_counts(n, [0.2, 0.8])

    assert sum(counts) == n
    assert counts[1] / n == pytest.approx(0.8, abs=0.01)


def test_every_mode_keeps_at_least_one_particle():
    """A mode the weighting judges negligible may just have a bad covariance;
    leaving it unrepresented is not something SMC can recover from."""
    counts = Laplace._stratified_counts(1000, [1e-12, 1.0])

    assert min(counts) >= 1
    assert sum(counts) == 1000


def test_degenerate_weights_fall_back_to_even_split():
    counts = Laplace._stratified_counts(100, [0.0, 0.0])

    assert counts == [50, 50]


def test_too_few_samples_for_the_modes_is_an_error():
    with pytest.raises(SamplerError, match="at least one per mode"):
        Laplace._stratified_counts(2, [0.3, 0.3, 0.4])


# --------------------------------------------------------------------------
# Wiring
# --------------------------------------------------------------------------


def test_unknown_mode_weights_is_rejected(sampler, estimator, monkeypatch):
    monkeypatch.setattr(
        Laplace, "_find_multiple_maps", lambda *a, **k: [(MEANS[0], TIGHT, 10.0), (MEANS[1], TIGHT, 10.0)]
    )
    sampler.kwargs["n_modes"] = 2
    sampler.kwargs["mode_weights"] = "bogus"

    with pytest.raises(SamplerError, match="mode_weights must be"):
        sampler._build_proposal(estimator, MEANS[0], TIGHT, 1)


def test_mode_search_subspace_defaults_to_none(sampler):
    assert sampler.kwargs["mode_search_subspace"] is None
    assert sampler.kwargs["mode_weights"] == "equal"


def test_subspace_pinning_keeps_other_coordinates_fixed():
    """The pinning arithmetic itself: only the named columns vary."""
    primary = np.array([1.0, 2.0, 3.0])
    draws = np.arange(12, dtype=float).reshape(4, 3)
    free = [0, 2]

    pinned = np.tile(primary, (len(draws), 1))
    pinned[:, free] = draws[:, free]

    np.testing.assert_array_equal(pinned[:, 1], np.full(4, 2.0))
    np.testing.assert_array_equal(pinned[:, 0], draws[:, 0])
    np.testing.assert_array_equal(pinned[:, 2], draws[:, 2])


# --------------------------------------------------------------------------
# Dropping negligible components.  A mode carrying ~0 of the Laplace mass is in
# practice a likelihood sidelobe the search turned up; seeding it a token
# particle puts a stray point in the diagnostics that cannot be sampled.
# --------------------------------------------------------------------------


def _modes(k):
    return [(np.array([float(i), 0.0]), TIGHT, 0.0) for i in range(k)]


def test_negligible_component_is_dropped(sampler):
    log_w = np.log(np.array([0.999, 1e-9]))

    kept, kept_log_w = sampler._drop_negligible_modes(_modes(2), log_w)

    assert len(kept) == 1
    assert len(kept_log_w) == 1
    assert kept[0][0][0] == 0.0


def test_comparable_components_are_all_kept(sampler):
    log_w = np.log(np.array([0.6, 0.4]))

    kept, kept_log_w = sampler._drop_negligible_modes(_modes(2), log_w)

    assert len(kept) == 2
    np.testing.assert_allclose(kept_log_w, log_w)


def test_a_component_just_above_threshold_survives(sampler):
    log_w = np.log(np.array([1.0 - 2e-3, 2e-3]))

    kept, _ = sampler._drop_negligible_modes(_modes(2), log_w)

    assert len(kept) == 2


def test_the_mixture_is_never_emptied(sampler):
    """Even if every weight underflows, the best mode is kept."""
    log_w = np.full(3, -np.inf)
    log_w[1] = -1e6

    kept, kept_log_w = sampler._drop_negligible_modes(_modes(3), log_w)

    assert len(kept) == 1
    assert len(kept_log_w) == 1
    assert kept[0][0][0] == 1.0


# --------------------------------------------------------------------------
# Mode separation threshold.  The dedup gate is a `max` over per-parameter
# normalised separations, applied both before polishing (skip a candidate near a
# known mode) and after (discard a duplicate).  On the HLV example the real
# second sky mode is 3.3 sigma out in azimuth and 2 sigma in zenith, so the
# hard-coded 3.0 rejected it and the search kept a distant sidelobe instead.
# --------------------------------------------------------------------------


def _separation(candidate, mode, std_scale):
    """The quantity the dedup gate thresholds."""
    return np.max(np.abs(np.asarray(candidate) - np.asarray(mode)) / np.asarray(std_scale))


def test_default_threshold_rejects_the_hlv_second_sky_mode():
    """Regression for the observed geometry: primary vs the real secondary."""
    primary = np.array([1.3787, 1.2103])  # azimuth, zenith at the primary MAP
    secondary = np.array([1.3150, 1.1920])  # centre of the real second island
    std_scale = np.array([0.0184, 0.0074])

    sep = _separation(secondary, primary, std_scale)

    assert 3.0 < sep < 3.6  # only just outside -- and the zenith axis is 2 sigma
    assert _separation(secondary, primary, std_scale * 1.2) < 3.0  # a nudge merges them


def test_lowering_the_threshold_admits_a_close_mode():
    primary, secondary = np.array([0.0, 0.0]), np.array([2.0, 1.0])
    std_scale = np.array([1.0, 1.0])

    sep = _separation(secondary, primary, std_scale)

    assert sep < 3.0  # rejected at the default
    assert sep > 1.5  # admitted once the threshold is lowered


def test_threshold_is_exposed_with_the_previous_default(sampler):
    assert sampler.kwargs["mode_separation_sigma"] == 3.0


@pytest.mark.parametrize("bad", [0.0, -1.0, float("nan"), float("inf")])
def test_invalid_threshold_is_rejected(sampler, estimator, bad):
    sampler.kwargs["mode_separation_sigma"] = bad
    sampler.kwargs["n_modes"] = 2

    with pytest.raises(SamplerError, match="mode_separation_sigma"):
        sampler._find_multiple_maps(estimator, 2, np.ones(2), np.zeros(2), np.eye(2))


# --------------------------------------------------------------------------
# The primary mode must be the one run_sampler already found, not a fresh
# search.  It used to run its own differential evolution here, ignoring
# `use_injection_for_map` and skipping the polish secondary candidates get --
# on the HLV example that landed 59-200 nats below the injection-seeded MAP,
# lengthening the SMC schedule from ~7 iterations to 15+ purely via the seed.
# --------------------------------------------------------------------------


def test_primary_mode_is_the_given_map(sampler, estimator):
    """n_modes>1 must be a superset of n_modes=1, not a different analysis."""
    sampler.kwargs["n_modes"] = 1  # take the early return, skipping the search
    mean = np.array([0.25, -0.4])
    cov = np.diag([0.3, 0.7])

    modes = sampler._find_multiple_maps(estimator, 1, np.ones(2), mean, cov)

    assert len(modes) == 1
    np.testing.assert_allclose(modes[0][0], mean)
    np.testing.assert_allclose(modes[0][1], cov)


def test_primary_covariance_is_not_re_validated(sampler, estimator):
    """The incoming covariance is already validated and scaled by run_sampler;
    re-applying either would double-count and desync the two paths."""
    mean = np.array([0.0, 0.0])
    cov = np.diag([1e-6, 1e-6])  # far too narrow; validation would inflate it
    sampler.kwargs["n_modes"] = 1

    modes = sampler._find_multiple_maps(estimator, 1, np.full(2, 4.0), mean, cov)

    np.testing.assert_allclose(modes[0][1], cov)


def test_no_global_optimisation_is_run_for_the_primary(sampler, estimator, monkeypatch):
    """Guards the regression directly: the DE call must be gone."""

    def _boom(*args, **kwargs):
        raise AssertionError("differential evolution must not run for the primary mode")

    monkeypatch.setattr(estimator, "_maximize_posterior_differential_evolution", _boom)
    sampler.kwargs["n_modes"] = 1

    sampler._find_multiple_maps(estimator, 1, np.ones(2), np.zeros(2), np.eye(2))


# --------------------------------------------------------------------------
# mode_searches: choosing which way(s) to look for secondary modes
# --------------------------------------------------------------------------
# The stochastic (`'hypercube'`) and exact (`'symmetric'`) searches can fail
# in opposite directions on the same problem: on a precessing-BBH example the
# hypercube search kept finding shallow local maxima that are geometry noise
# -- one held under 1% of the posterior mass by an independent reference yet
# took 70% of the proposal weight -- while the exact delta_phase symmetry on
# the same problem is essential (without it the run samples one lobe of two).
# No re-weighting of the mixture fixed the first problem, because the damage
# is which points enter the mixture, not how they are weighted once they do.
# `mode_searches=['symmetric']` runs only the search that helps.

import bilby  # noqa: E402
from conftest import MU, TRUE_COV  # noqa: E402


class _PeriodicSymmetricLikelihood(bilby.core.likelihood.Likelihood):
    """A 2-D likelihood exactly periodic in ``phi`` with period pi.

    ``log_likelihood(phi + pi) == log_likelihood(phi)`` to machine precision
    by construction (``cos(2 * theta)`` has period pi), giving two mirror
    modes of identical height -- the same structure ``mode_symmetries``
    targets on the precessing-BBH example's ``delta_phase``, in a fixture
    cheap enough to optimise in a unit test.
    """

    MU_X, SIGMA_X = 1.0, 0.3
    MU_PHI, KAPPA = 0.7, 50.0

    def __init__(self):
        super().__init__(parameters=dict(x=None, phi=None))

    def log_likelihood(self, parameters=None):
        p = parameters if parameters is not None else self.parameters
        dx = (p["x"] - self.MU_X) / self.SIGMA_X
        return -0.5 * dx**2 + self.KAPPA * np.cos(2.0 * (p["phi"] - self.MU_PHI))


@pytest.fixture
def periodic_priors():
    return bilby.core.prior.PriorDict(
        dict(
            x=bilby.core.prior.Uniform(-5.0, 5.0, "x"),
            phi=bilby.core.prior.Uniform(0.0, 2 * np.pi, "phi", boundary="periodic"),
        )
    )


@pytest.fixture
def periodic_estimator(periodic_priors):
    from bilby_laplace.laplace import LaplacePosteriorEstimator

    return LaplacePosteriorEstimator(_PeriodicSymmetricLikelihood(), periodic_priors)


@pytest.fixture
def periodic_sampler(periodic_priors, tmp_path):
    """A ``Laplace`` bound to the periodic fixture's own likelihood/priors.

    ``_latin_hypercube_prior`` reads ``self.priors`` on the *sampler*, not on
    whatever estimator a test happens to pass in -- so exercising the real
    hypercube path against ``periodic_estimator`` needs a sampler built on
    the same priors, unlike the plain ``sampler`` fixture (bound to
    conftest's unrelated x/y Gaussian).
    """
    return Laplace(
        likelihood=_PeriodicSymmetricLikelihood(),
        priors=periodic_priors,
        outdir=str(tmp_path),
        label="test-periodic",
    )


@pytest.fixture
def periodic_mode(periodic_estimator):
    """The primary mode at the fixture's construction, no optimiser needed."""
    L = _PeriodicSymmetricLikelihood
    mean = np.array([L.MU_X, L.MU_PHI])
    # Local curvature: -d^2/dx^2 of each term at the peak.
    cov = np.diag([L.SIGMA_X**2, 1.0 / (4.0 * L.KAPPA)])
    logp = float(periodic_estimator.log_posterior_from_array(mean))
    return mean, cov, logp


def test_mode_searches_default_runs_both(sampler):
    assert set(sampler.kwargs["mode_searches"]) == {"hypercube", "symmetric"}


def test_unknown_mode_search_is_rejected(sampler, estimator):
    sampler.kwargs["mode_searches"] = ["hypercube", "nonsense"]

    with pytest.raises(SamplerError, match="mode_searches"):
        sampler._find_multiple_maps(estimator, 2, np.ones(2), MU.copy(), TRUE_COV.copy())


def test_symmetric_only_skips_the_stochastic_search(sampler, estimator, monkeypatch):
    """No mode_symmetries declared: 'symmetric' alone must add nothing, and
    must not fall through to the hypercube search it was asked to skip."""

    def _boom(*args, **kwargs):
        raise AssertionError("mode_searches=['symmetric'] must not run the hypercube search")

    monkeypatch.setattr(sampler, "_latin_hypercube_prior", _boom)
    sampler.kwargs["mode_searches"] = ["symmetric"]
    sampler.kwargs["mode_symmetries"] = None

    modes = sampler._find_multiple_maps(estimator, 2, np.ones(2), MU.copy(), TRUE_COV.copy())

    assert len(modes) == 1


def test_hypercube_only_does_not_seed_the_symmetry(sampler, periodic_estimator, periodic_mode, monkeypatch):
    """The mirror-image case: 'hypercube' alone must leave a declared
    symmetry unseeded, even though it would otherwise be free to add."""
    mean, cov, logp = periodic_mode
    monkeypatch.setattr(sampler, "_latin_hypercube_prior", lambda *a, **k: np.empty((0, 2)))
    sampler.kwargs["mode_searches"] = ["hypercube"]
    sampler.kwargs["mode_symmetries"] = [("phi", np.pi)]
    sampler.kwargs["mode_search_subspace"] = None

    modes = sampler._find_multiple_maps(periodic_estimator, 2, np.ones(2), mean, cov)

    assert len(modes) == 1


def test_symmetric_only_seeds_the_exact_mirror(sampler, periodic_estimator, periodic_mode, monkeypatch):
    """The fix, end to end: the mirror is found, matches the source mode's
    log-posterior exactly, and no stochastic evaluation ever ran."""
    mean, cov, logp = periodic_mode

    def _boom(*args, **kwargs):
        raise AssertionError("mode_searches=['symmetric'] must not run the hypercube search")

    monkeypatch.setattr(sampler, "_latin_hypercube_prior", _boom)
    sampler.kwargs["mode_searches"] = ["symmetric"]
    sampler.kwargs["mode_symmetries"] = [("phi", np.pi)]

    modes = sampler._find_multiple_maps(periodic_estimator, 2, np.ones(2), mean, cov)

    assert len(modes) == 2
    mirror = modes[1] if modes[0][0] is mean or np.allclose(modes[0][0], mean) else modes[0]
    np.testing.assert_allclose(mirror[0][0], mean[0])  # x untouched by the phi symmetry
    assert mirror[0][1] == pytest.approx((mean[1] + np.pi) % (2 * np.pi), abs=1e-6)
    assert mirror[2] == pytest.approx(logp, abs=1e-6)  # exact symmetry: heights match


def test_symmetric_only_is_a_real_alternative_to_default(periodic_sampler, periodic_estimator, periodic_mode):
    """Sanity check on the fixture itself: the default (both searches) finds
    the same mirror 'symmetric' alone does, so the two are comparable."""
    mean, cov, _logp = periodic_mode
    periodic_sampler.kwargs["mode_search_nsamples"] = 200
    periodic_sampler.kwargs["mode_symmetries"] = [("phi", np.pi)]
    periodic_sampler.kwargs["mode_search_subspace"] = None
    periodic_sampler.kwargs["mode_separation_sigma"] = 1.0

    modes = periodic_sampler._find_multiple_maps(periodic_estimator, 2, np.ones(2), mean.copy(), cov.copy())

    phis = sorted(m[0][1] for m in modes)
    assert phis[0] == pytest.approx(mean[1], abs=1e-3)
    assert phis[-1] == pytest.approx((mean[1] + np.pi) % (2 * np.pi), abs=1e-3)

