"""Tests for subspace-restricted mode search and Laplace-weighted mixtures.

Two related gaps in the multi-mode path:

* Candidates were only ever generated by a Latin hypercube over the *full*
  parameter space, so a narrow secondary mode was undiscoverable -- a GW sky
  reflection a few 0.01 rad across is ~1e-4 of the sky.  ``mode_search_subspace``
  varies only the coordinates the degeneracy lives in.
* Components were weighted equally, which ignores that a broad shallow mode
  holds more posterior mass than a narrow tall one.  ``mode_weights='laplace'``
  weights by each mode's Laplace local evidence.
"""

import numpy as np
import pytest
from bilby.core.sampler.base_sampler import SamplerError

from bilby_laplace.sampler import GaussianMixtureFlow, Laplace

MEANS = [np.array([-3.0, 0.0]), np.array([3.0, 0.0])]
TIGHT = np.diag([0.04, 0.04])
BROAD = np.diag([1.0, 1.0])


# --------------------------------------------------------------------------
# GaussianMixtureFlow weighting
# --------------------------------------------------------------------------


def test_equal_weights_by_default():
    flow = GaussianMixtureFlow(MEANS, [TIGHT, TIGHT])

    np.testing.assert_allclose(flow.weights, [0.5, 0.5])


def test_log_weights_are_normalised():
    """Unnormalised log-evidences must be accepted directly."""
    flow = GaussianMixtureFlow(MEANS, [TIGHT, TIGHT], log_weights=[1000.0, 1000.0 + np.log(3.0)])

    np.testing.assert_allclose(flow.weights, [0.25, 0.75], rtol=1e-9)


def test_log_weights_must_match_component_count():
    with pytest.raises(ValueError, match="one entry per component"):
        GaussianMixtureFlow(MEANS, [TIGHT, TIGHT], log_weights=[0.0, 0.0, 0.0])


def test_weighted_log_prob_integrates_to_one():
    """The density must stay normalised once weights are unequal."""
    flow = GaussianMixtureFlow(MEANS, [TIGHT, TIGHT], log_weights=[np.log(0.2), np.log(0.8)])
    grid = np.linspace(-8, 8, 400)
    xx, yy = np.meshgrid(grid, grid)
    pts = np.column_stack([xx.ravel(), yy.ravel()])
    cell = (grid[1] - grid[0]) ** 2

    total = np.exp(flow.log_prob(pts)).sum() * cell

    assert total == pytest.approx(1.0, abs=1e-3)


def test_log_prob_handles_single_points_and_batches():
    """Both branches must apply the weight vector.

    ``multivariate_normal.logpdf`` collapses a single-row 2-D input to a scalar,
    so the ``(K,)`` shape covers a bare point *and* a one-row batch; only a
    genuinely multi-row input reaches the ``(K, N)`` branch.
    """
    from scipy.special import logsumexp
    from scipy.stats import multivariate_normal

    log_w = np.log(np.array([0.1, 0.9]))
    flow = GaussianMixtureFlow(MEANS, [TIGHT, TIGHT], log_weights=log_w)

    def expected(point):
        per = [multivariate_normal(mean=m, cov=TIGHT).logpdf(point) for m in MEANS]
        return logsumexp(np.array(per) + log_w)

    assert float(flow.log_prob(MEANS[1])) == pytest.approx(expected(MEANS[1]))
    assert float(flow.log_prob(np.atleast_2d(MEANS[1]))) == pytest.approx(expected(MEANS[1]))

    batch = np.vstack([MEANS[0], MEANS[1], np.zeros(2)])
    out = flow.log_prob(batch)
    assert out.shape == (3,)
    for i, row in enumerate(batch):
        assert out[i] == pytest.approx(expected(row))


def test_sampling_follows_the_weights(monkeypatch):
    flow = GaussianMixtureFlow(MEANS, [TIGHT, TIGHT], log_weights=[np.log(0.2), np.log(0.8)])

    x, _ = flow.sample_and_log_prob(4000)

    assert np.mean(x[:, 0] > 0) == pytest.approx(0.8, abs=0.03)


# --------------------------------------------------------------------------
# Laplace weighting: volume, not just height
# --------------------------------------------------------------------------


def test_broad_mode_can_outweigh_a_taller_narrow_one():
    """The point of the feature.  Equal log-posterior, different widths."""
    modes = [(MEANS[0], TIGHT, 10.0), (MEANS[1], BROAD, 10.0)]

    log_w = Laplace._laplace_mode_log_weights(modes, ndim=2)

    assert log_w[1] > log_w[0]
    # det ratio is (1/0.04)^2 = 625, so the broad mode carries 25x the mass.
    assert np.exp(log_w[1] - log_w[0]) == pytest.approx(25.0, rel=1e-6)


def test_weighting_by_peak_height_alone_would_disagree():
    """A narrow mode with a higher peak still loses if it is narrow enough."""
    modes = [(MEANS[0], TIGHT, 12.0), (MEANS[1], BROAD, 10.0)]

    log_w = Laplace._laplace_mode_log_weights(modes, ndim=2)

    assert modes[0][2] > modes[1][2]  # taller peak...
    assert log_w[1] > log_w[0]  # ...but less mass


def test_laplace_weight_matches_the_analytic_evidence():
    modes = [(MEANS[0], TIGHT, 10.0)]

    log_w = Laplace._laplace_mode_log_weights(modes, ndim=2)

    expected = 10.0 + 0.5 * 2 * np.log(2 * np.pi) + 0.5 * np.log(np.linalg.det(TIGHT))
    assert log_w[0] == pytest.approx(expected)


def test_non_positive_definite_covariance_falls_back_to_log_posterior():
    modes = [(MEANS[0], np.array([[1.0, 0.0], [0.0, -1.0]]), 7.0)]

    log_w = Laplace._laplace_mode_log_weights(modes, ndim=2)

    assert log_w[0] == pytest.approx(7.0)


# --------------------------------------------------------------------------
# Stratified apportionment of the initial cloud
# --------------------------------------------------------------------------


@pytest.mark.parametrize("n", [1000, 1001, 999])
def test_counts_sum_to_n_and_follow_the_weights(n):
    counts = Laplace._stratified_counts(n, [0.2, 0.8])

    assert sum(counts) == n
    assert counts[1] / n == pytest.approx(0.8, abs=0.01)


def test_every_mode_keeps_at_least_one_particle():
    """A mode the weighting judges negligible may just have a bad covariance;
    leaving it unrepresented is not something SMC can recover from."""
    counts = Laplace._stratified_counts(1000, [1e-12, 1.0])

    assert min(counts) >= 1
    assert sum(counts) == 1000


def test_degenerate_weights_fall_back_to_even_split():
    counts = Laplace._stratified_counts(100, [0.0, 0.0])

    assert counts == [50, 50]


def test_too_few_samples_for_the_modes_is_an_error():
    with pytest.raises(SamplerError, match="at least one per mode"):
        Laplace._stratified_counts(2, [0.3, 0.3, 0.4])


# --------------------------------------------------------------------------
# Wiring
# --------------------------------------------------------------------------


def test_unknown_mode_weights_is_rejected(sampler, estimator, monkeypatch):
    monkeypatch.setattr(
        Laplace, "_find_multiple_maps", lambda *a, **k: [(MEANS[0], TIGHT, 10.0), (MEANS[1], TIGHT, 10.0)]
    )
    sampler.kwargs["n_modes"] = 2
    sampler.kwargs["mode_weights"] = "bogus"

    with pytest.raises(SamplerError, match="mode_weights must be"):
        sampler._build_proposal(estimator, MEANS[0], TIGHT, 1)


def test_mode_search_subspace_defaults_to_none(sampler):
    assert sampler.kwargs["mode_search_subspace"] is None
    assert sampler.kwargs["mode_weights"] == "equal"


def test_subspace_pinning_keeps_other_coordinates_fixed():
    """The pinning arithmetic itself: only the named columns vary."""
    primary = np.array([1.0, 2.0, 3.0])
    draws = np.arange(12, dtype=float).reshape(4, 3)
    free = [0, 2]

    pinned = np.tile(primary, (len(draws), 1))
    pinned[:, free] = draws[:, free]

    np.testing.assert_array_equal(pinned[:, 1], np.full(4, 2.0))
    np.testing.assert_array_equal(pinned[:, 0], draws[:, 0])
    np.testing.assert_array_equal(pinned[:, 2], draws[:, 2])


# --------------------------------------------------------------------------
# Dropping negligible components.  A mode carrying ~0 of the Laplace mass is in
# practice a likelihood sidelobe the search turned up; seeding it a token
# particle puts a stray point in the diagnostics that cannot be sampled.
# --------------------------------------------------------------------------


def _modes(k):
    return [(np.array([float(i), 0.0]), TIGHT, 0.0) for i in range(k)]


def test_negligible_component_is_dropped(sampler):
    log_w = np.log(np.array([0.999, 1e-9]))

    kept, kept_log_w = sampler._drop_negligible_modes(_modes(2), log_w)

    assert len(kept) == 1
    assert len(kept_log_w) == 1
    assert kept[0][0][0] == 0.0


def test_comparable_components_are_all_kept(sampler):
    log_w = np.log(np.array([0.6, 0.4]))

    kept, kept_log_w = sampler._drop_negligible_modes(_modes(2), log_w)

    assert len(kept) == 2
    np.testing.assert_allclose(kept_log_w, log_w)


def test_a_component_just_above_threshold_survives(sampler):
    log_w = np.log(np.array([1.0 - 2e-3, 2e-3]))

    kept, _ = sampler._drop_negligible_modes(_modes(2), log_w)

    assert len(kept) == 2


def test_the_mixture_is_never_emptied(sampler):
    """Even if every weight underflows, the best mode is kept."""
    log_w = np.full(3, -np.inf)
    log_w[1] = -1e6

    kept, kept_log_w = sampler._drop_negligible_modes(_modes(3), log_w)

    assert len(kept) == 1
    assert len(kept_log_w) == 1
    assert kept[0][0][0] == 1.0


# --------------------------------------------------------------------------
# Mode separation threshold.  The dedup gate is a `max` over per-parameter
# normalised separations, applied both before polishing (skip a candidate near a
# known mode) and after (discard a duplicate).  On the HLV example the real
# second sky mode is 3.3 sigma out in azimuth and 2 sigma in zenith, so the
# hard-coded 3.0 rejected it and the search kept a distant sidelobe instead.
# --------------------------------------------------------------------------


def _separation(candidate, mode, std_scale):
    """The quantity the dedup gate thresholds."""
    return np.max(np.abs(np.asarray(candidate) - np.asarray(mode)) / np.asarray(std_scale))


def test_default_threshold_rejects_the_hlv_second_sky_mode():
    """Regression for the observed geometry: primary vs the real secondary."""
    primary = np.array([1.3787, 1.2103])  # azimuth, zenith at the primary MAP
    secondary = np.array([1.3150, 1.1920])  # centre of the real second island
    std_scale = np.array([0.0184, 0.0074])

    sep = _separation(secondary, primary, std_scale)

    assert 3.0 < sep < 3.6  # only just outside -- and the zenith axis is 2 sigma
    assert _separation(secondary, primary, std_scale * 1.2) < 3.0  # a nudge merges them


def test_lowering_the_threshold_admits_a_close_mode():
    primary, secondary = np.array([0.0, 0.0]), np.array([2.0, 1.0])
    std_scale = np.array([1.0, 1.0])

    sep = _separation(secondary, primary, std_scale)

    assert sep < 3.0  # rejected at the default
    assert sep > 1.5  # admitted once the threshold is lowered


def test_threshold_is_exposed_with_the_previous_default(sampler):
    assert sampler.kwargs["mode_separation_sigma"] == 3.0


@pytest.mark.parametrize("bad", [0.0, -1.0, float("nan"), float("inf")])
def test_invalid_threshold_is_rejected(sampler, estimator, bad):
    sampler.kwargs["mode_separation_sigma"] = bad
    sampler.kwargs["n_modes"] = 2

    with pytest.raises(SamplerError, match="mode_separation_sigma"):
        sampler._find_multiple_maps(estimator, 2, np.ones(2), np.zeros(2), np.eye(2))


# --------------------------------------------------------------------------
# The primary mode must be the one run_sampler already found, not a fresh
# search.  It used to run its own differential evolution here, ignoring
# `use_injection_for_map` and skipping the polish secondary candidates get --
# on the HLV example that landed 59-200 nats below the injection-seeded MAP,
# lengthening the SMC schedule from ~7 iterations to 15+ purely via the seed.
# --------------------------------------------------------------------------


def test_primary_mode_is_the_given_map(sampler, estimator):
    """n_modes>1 must be a superset of n_modes=1, not a different analysis."""
    sampler.kwargs["n_modes"] = 1  # take the early return, skipping the search
    mean = np.array([0.25, -0.4])
    cov = np.diag([0.3, 0.7])

    modes = sampler._find_multiple_maps(estimator, 1, np.ones(2), mean, cov)

    assert len(modes) == 1
    np.testing.assert_allclose(modes[0][0], mean)
    np.testing.assert_allclose(modes[0][1], cov)


def test_primary_covariance_is_not_re_validated(sampler, estimator):
    """The incoming covariance is already validated and scaled by run_sampler;
    re-applying either would double-count and desync the two paths."""
    mean = np.array([0.0, 0.0])
    cov = np.diag([1e-6, 1e-6])  # far too narrow; validation would inflate it
    sampler.kwargs["n_modes"] = 1

    modes = sampler._find_multiple_maps(estimator, 1, np.full(2, 4.0), mean, cov)

    np.testing.assert_allclose(modes[0][1], cov)


def test_no_global_optimisation_is_run_for_the_primary(sampler, estimator, monkeypatch):
    """Guards the regression directly: the DE call must be gone."""

    def _boom(*args, **kwargs):
        raise AssertionError("differential evolution must not run for the primary mode")

    monkeypatch.setattr(estimator, "_maximize_posterior_differential_evolution", _boom)
    sampler.kwargs["n_modes"] = 1

    sampler._find_multiple_maps(estimator, 1, np.ones(2), np.zeros(2), np.eye(2))


# --------------------------------------------------------------------------
# mode_searches: choosing which way(s) to look for secondary modes
# --------------------------------------------------------------------------
# The stochastic (`'hypercube'`) and exact (`'symmetric'`) searches can fail
# in opposite directions on the same problem: on a precessing-BBH example the
# hypercube search kept finding shallow local maxima that are geometry noise
# -- one held under 1% of the posterior mass by an independent reference yet
# took 70% of the proposal weight -- while the exact delta_phase symmetry on
# the same problem is essential (without it the run samples one lobe of two).
# No re-weighting of the mixture fixed the first problem, because the damage
# is which points enter the mixture, not how they are weighted once they do.
# `mode_searches=['symmetric']` runs only the search that helps.

import bilby  # noqa: E402
from conftest import MU, TRUE_COV  # noqa: E402


class _PeriodicSymmetricLikelihood(bilby.core.likelihood.Likelihood):
    """A 2-D likelihood exactly periodic in ``phi`` with period pi.

    ``log_likelihood(phi + pi) == log_likelihood(phi)`` to machine precision
    by construction (``cos(2 * theta)`` has period pi), giving two mirror
    modes of identical height -- the same structure ``mode_symmetries``
    targets on the precessing-BBH example's ``delta_phase``, in a fixture
    cheap enough to optimise in a unit test.
    """

    MU_X, SIGMA_X = 1.0, 0.3
    MU_PHI, KAPPA = 0.7, 50.0

    def __init__(self):
        super().__init__(parameters=dict(x=None, phi=None))

    def log_likelihood(self, parameters=None):
        p = parameters if parameters is not None else self.parameters
        dx = (p["x"] - self.MU_X) / self.SIGMA_X
        return -0.5 * dx**2 + self.KAPPA * np.cos(2.0 * (p["phi"] - self.MU_PHI))


@pytest.fixture
def periodic_priors():
    return bilby.core.prior.PriorDict(
        dict(
            x=bilby.core.prior.Uniform(-5.0, 5.0, "x"),
            phi=bilby.core.prior.Uniform(0.0, 2 * np.pi, "phi", boundary="periodic"),
        )
    )


@pytest.fixture
def periodic_estimator(periodic_priors):
    from bilby_laplace.laplace import LaplacePosteriorEstimator

    return LaplacePosteriorEstimator(_PeriodicSymmetricLikelihood(), periodic_priors)


@pytest.fixture
def periodic_sampler(periodic_priors, tmp_path):
    """A ``Laplace`` bound to the periodic fixture's own likelihood/priors.

    ``_latin_hypercube_prior`` reads ``self.priors`` on the *sampler*, not on
    whatever estimator a test happens to pass in -- so exercising the real
    hypercube path against ``periodic_estimator`` needs a sampler built on
    the same priors, unlike the plain ``sampler`` fixture (bound to
    conftest's unrelated x/y Gaussian).
    """
    return Laplace(
        likelihood=_PeriodicSymmetricLikelihood(),
        priors=periodic_priors,
        outdir=str(tmp_path),
        label="test-periodic",
    )


@pytest.fixture
def periodic_mode(periodic_estimator):
    """The primary mode at the fixture's construction, no optimiser needed."""
    L = _PeriodicSymmetricLikelihood
    mean = np.array([L.MU_X, L.MU_PHI])
    # Local curvature: -d^2/dx^2 of each term at the peak.
    cov = np.diag([L.SIGMA_X**2, 1.0 / (4.0 * L.KAPPA)])
    logp = float(periodic_estimator.log_posterior_from_array(mean))
    return mean, cov, logp


def test_mode_searches_default_runs_both(sampler):
    assert set(sampler.kwargs["mode_searches"]) == {"hypercube", "symmetric"}


def test_unknown_mode_search_is_rejected(sampler, estimator):
    sampler.kwargs["mode_searches"] = ["hypercube", "nonsense"]

    with pytest.raises(SamplerError, match="mode_searches"):
        sampler._find_multiple_maps(estimator, 2, np.ones(2), MU.copy(), TRUE_COV.copy())


def test_symmetric_only_skips_the_stochastic_search(sampler, estimator, monkeypatch):
    """No mode_symmetries declared: 'symmetric' alone must add nothing, and
    must not fall through to the hypercube search it was asked to skip."""

    def _boom(*args, **kwargs):
        raise AssertionError("mode_searches=['symmetric'] must not run the hypercube search")

    monkeypatch.setattr(sampler, "_latin_hypercube_prior", _boom)
    sampler.kwargs["mode_searches"] = ["symmetric"]
    sampler.kwargs["mode_symmetries"] = None

    modes = sampler._find_multiple_maps(estimator, 2, np.ones(2), MU.copy(), TRUE_COV.copy())

    assert len(modes) == 1


def test_hypercube_only_does_not_seed_the_symmetry(sampler, periodic_estimator, periodic_mode, monkeypatch):
    """The mirror-image case: 'hypercube' alone must leave a declared
    symmetry unseeded, even though it would otherwise be free to add."""
    mean, cov, logp = periodic_mode
    monkeypatch.setattr(sampler, "_latin_hypercube_prior", lambda *a, **k: np.empty((0, 2)))
    sampler.kwargs["mode_searches"] = ["hypercube"]
    sampler.kwargs["mode_symmetries"] = [("phi", np.pi)]
    sampler.kwargs["mode_search_subspace"] = None

    modes = sampler._find_multiple_maps(periodic_estimator, 2, np.ones(2), mean, cov)

    assert len(modes) == 1


def test_symmetric_only_seeds_the_exact_mirror(sampler, periodic_estimator, periodic_mode, monkeypatch):
    """The fix, end to end: the mirror is found, matches the source mode's
    log-posterior exactly, and no stochastic evaluation ever ran."""
    mean, cov, logp = periodic_mode

    def _boom(*args, **kwargs):
        raise AssertionError("mode_searches=['symmetric'] must not run the hypercube search")

    monkeypatch.setattr(sampler, "_latin_hypercube_prior", _boom)
    sampler.kwargs["mode_searches"] = ["symmetric"]
    sampler.kwargs["mode_symmetries"] = [("phi", np.pi)]

    modes = sampler._find_multiple_maps(periodic_estimator, 2, np.ones(2), mean, cov)

    assert len(modes) == 2
    mirror = modes[1] if modes[0][0] is mean or np.allclose(modes[0][0], mean) else modes[0]
    np.testing.assert_allclose(mirror[0][0], mean[0])  # x untouched by the phi symmetry
    assert mirror[0][1] == pytest.approx((mean[1] + np.pi) % (2 * np.pi), abs=1e-6)
    assert mirror[2] == pytest.approx(logp, abs=1e-6)  # exact symmetry: heights match


def test_symmetric_only_is_a_real_alternative_to_default(periodic_sampler, periodic_estimator, periodic_mode):
    """Sanity check on the fixture itself: the default (both searches) finds
    the same mirror 'symmetric' alone does, so the two are comparable."""
    mean, cov, _logp = periodic_mode
    periodic_sampler.kwargs["mode_search_nsamples"] = 200
    periodic_sampler.kwargs["mode_symmetries"] = [("phi", np.pi)]
    periodic_sampler.kwargs["mode_search_subspace"] = None
    periodic_sampler.kwargs["mode_separation_sigma"] = 1.0

    modes = periodic_sampler._find_multiple_maps(periodic_estimator, 2, np.ones(2), mean.copy(), cov.copy())

    phis = sorted(m[0][1] for m in modes)
    assert phis[0] == pytest.approx(mean[1], abs=1e-3)
    assert phis[-1] == pytest.approx((mean[1] + np.pi) % (2 * np.pi), abs=1e-3)


# --- Approximate symmetries -------------------------------------------------
#
# `mode_symmetries` used to demand an *exact* mirror (0.5 nats), which rejected
# modes precisely where they matter: on the XPHM BBH_HLV example the delta_phase
# mirror missed by 1.12 nats and was skipped, yet dynesty and aspire both put
# 0.22-0.27 of the posterior in that lobe, and losing it cost a 468 mbit JSD.
# The tolerance is now a floor on how much mass an implied mode must carry.


class _TiltedPeriodicLikelihood(_PeriodicSymmetricLikelihood):
    """As the exact fixture, but with the pi-mirror tilted by a known offset.

    Adding ``TILT * cos(phi - MU_PHI)`` leaves the pi-periodic structure intact
    -- there are still two lobes -- but breaks their equality, exactly as
    higher modes break the delta_phase degeneracy on a real BBH. At the mode
    the tilt contributes ``+TILT``, at its mirror ``-TILT``, so the two differ
    by ``2 * TILT`` nats and the mirror's share of the pair is ``exp(-2*TILT)``.
    """

    TILT = 0.56  # -> offset 1.12 nats, matching what BBH_HLV actually showed

    def log_likelihood(self, parameters=None):
        p = parameters if parameters is not None else self.parameters
        base = super().log_likelihood(p)
        return base + self.TILT * np.cos(p["phi"] - self.MU_PHI)


@pytest.fixture
def tilted_estimator(periodic_priors):
    from bilby_laplace.laplace import LaplacePosteriorEstimator

    return LaplacePosteriorEstimator(_TiltedPeriodicLikelihood(), periodic_priors)


def _seed_symmetry(sampler, estimator, monkeypatch, tol=None):
    """Run only the symmetric search on *estimator*, returning the modes."""

    def _boom(*args, **kwargs):
        raise AssertionError("this test must not run the hypercube search")

    monkeypatch.setattr(sampler, "_latin_hypercube_prior", _boom)
    sampler.kwargs["mode_searches"] = ["symmetric"]
    sampler.kwargs["mode_symmetries"] = [("phi", np.pi)]
    sampler.kwargs["mode_symmetry_tol"] = tol
    # The tilt shifts the peak slightly off MU_PHI; locate it on a fine grid so
    # the fixture stays analytic rather than depending on the optimiser.
    L = _TiltedPeriodicLikelihood
    grid = np.linspace(0.0, 2 * np.pi, 20001)
    lp = np.array([estimator.log_posterior_from_array(np.array([L.MU_X, g])) for g in grid])
    mean = np.array([L.MU_X, grid[int(np.argmax(lp))]])
    cov = np.diag([L.SIGMA_X**2, 1.0 / (4.0 * L.KAPPA)])
    logp = float(estimator.log_posterior_from_array(mean))
    modes = sampler._find_multiple_maps(estimator, 2, np.ones(2), mean, cov)
    return modes, (mean, logp)


def test_approximate_symmetry_is_seeded(sampler, tilted_estimator, monkeypatch):
    """A mirror that misses by ~1.12 nats -- the BBH_HLV case -- is seeded, and
    carries its own (lower) log-posterior rather than its source's."""
    modes, (mean, logp) = _seed_symmetry(sampler, tilted_estimator, monkeypatch)

    assert len(modes) == 2, "the approximate mirror should have been seeded"
    mirror = modes[1] if np.allclose(modes[0][0], mean) else modes[0]
    offset = abs(mirror[2] - logp)
    assert 0.5 < offset < 3.0, f"fixture should sit above the old 0.5 tol, got {offset}"
    assert mirror[2] < logp, "the tilted mirror must be the shallower lobe"


def test_exact_tolerance_still_rejects_an_approximate_mirror(sampler, tilted_estimator, monkeypatch):
    """mode_symmetry_tol=0 restores the old exact-only behaviour."""
    modes, _ = _seed_symmetry(sampler, tilted_estimator, monkeypatch, tol=0.0)
    assert len(modes) == 1, "tol=0 must demand an exact symmetry"


def test_fictitious_symmetry_is_still_rejected(sampler, periodic_estimator, periodic_mode, monkeypatch):
    """A symmetry the posterior does not have must still be skipped: the point
    of widening the tolerance is to admit real modes, not fictitious ones."""

    def _boom(*args, **kwargs):
        raise AssertionError("this test must not run the hypercube search")

    monkeypatch.setattr(sampler, "_latin_hypercube_prior", _boom)
    mean, cov, _ = periodic_mode
    sampler.kwargs["mode_searches"] = ["symmetric"]
    # phi is pi-periodic, so a pi/2 shift lands on a trough, not a mode.
    sampler.kwargs["mode_symmetries"] = [("phi", np.pi / 2)]
    sampler.kwargs["mode_symmetry_tol"] = None

    modes = sampler._find_multiple_maps(periodic_estimator, 2, np.ones(2), mean, cov)
    assert len(modes) == 1


def test_default_tolerance_matches_the_negligible_weight_threshold(sampler):
    """The default tolerance is tied to _MIN_MODE_WEIGHT, so a symmetry mode is
    admitted exactly when it would survive _drop_negligible_modes."""
    assert sampler._SYMMETRY_LOGP_TOL == pytest.approx(-np.log(sampler._MIN_MODE_WEIGHT))
    assert np.exp(-sampler._SYMMETRY_LOGP_TOL) == pytest.approx(sampler._MIN_MODE_WEIGHT)


def test_negative_tolerance_is_rejected(sampler, periodic_estimator, periodic_mode):
    mean, cov, _ = periodic_mode
    sampler.kwargs["mode_searches"] = ["symmetric"]
    sampler.kwargs["mode_symmetries"] = [("phi", np.pi)]
    sampler.kwargs["mode_symmetry_tol"] = -1.0
    with pytest.raises(ValueError, match="non-negative"):
        sampler._find_multiple_maps(periodic_estimator, 2, np.ones(2), mean, cov)


# --- Full-space multi-start ------------------------------------------------
#
# 'hypercube' ranks its starts by log-posterior *before* polishing, so a mode
# whose basin is shallow where you land but deep where it leads is discarded
# before it is followed. On GW150914 the face-on solution is 24-51 nats down
# under any coordinate pinning and 37 under a theta_jn reflection, yet a plain
# local optimisation from a random prior draw reaches it 30% of the time.


class _HiddenBasinLikelihood(bilby.core.likelihood.Likelihood):
    """Two modes separated in a coordinate the subspace search cannot vary.

    The primary sits at ``(1, 0)``; the secondary at ``(-3, 3)`` is narrow in
    ``y``. With ``mode_search_subspace=['x']`` every hypercube start is pinned
    at the primary's ``y = 0``, where the secondary term is ``exp(-50)`` and the
    gradient points back to the primary -- so a start on that line polishes
    into the mode it already has and is discarded as a duplicate. The full-space
    multi-start draws ``y`` freely and descends into the secondary directly.

    This is GW150914's geometry in two dimensions: its face-on mode needs
    ``theta_jn`` to move, ``theta_jn`` is not in the subspace, and pinning it at
    the primary MAP leaves that mode 24-51 nats down.
    """

    A_MU, A_SIG, A_AMP = np.array([1.0, 0.0]), 0.8, 12.0  # primary
    B_MU, B_SIG, B_AMP = np.array([-3.0, 3.0]), 0.30, 10.0  # real secondary, off the subspace line
    # Decoys on the y = 0 line, so a subspace search over x finds them, well
    # separated in x so they survive deduplication, and shallower than the real
    # secondary so merit-based selection prefers it. These stand in for
    # GW150914's near-duplicate azimuth modes, which filled every slot.
    D_MU = (np.array([-1.3, 0.0]), np.array([3.7, 0.0]))
    D_SIG, D_AMP = 0.35, (8.5, 8.3)

    def __init__(self):
        super().__init__(parameters=dict(x=None, y=None))

    def log_likelihood(self, parameters=None):
        p = parameters if parameters is not None else self.parameters
        v = np.array([p["x"], p["y"]], dtype=float)
        terms = [
            self.A_AMP - 0.5 * np.sum(((v - self.A_MU) / self.A_SIG) ** 2),
            self.B_AMP - 0.5 * np.sum(((v - self.B_MU) / self.B_SIG) ** 2),
        ]
        for mu, amp in zip(self.D_MU, self.D_AMP):
            terms.append(amp - 0.5 * np.sum(((v - mu) / self.D_SIG) ** 2))
        return float(np.logaddexp.reduce(terms))


@pytest.fixture
def hidden_priors():
    return bilby.core.prior.PriorDict(
        dict(
            x=bilby.core.prior.Uniform(-5.0, 5.0, "x"),
            y=bilby.core.prior.Uniform(-5.0, 5.0, "y"),
        )
    )


@pytest.fixture
def hidden_estimator(hidden_priors):
    from bilby_laplace.laplace import LaplacePosteriorEstimator

    return LaplacePosteriorEstimator(
        _HiddenBasinLikelihood(), hidden_priors, minimization_method="Nelder-Mead", n_prior_samples=10
    )


@pytest.fixture
def hidden_primary(hidden_estimator):
    L = _HiddenBasinLikelihood
    mean = L.A_MU.astype(float).copy()
    cov = np.diag([L.A_SIG**2, L.A_SIG**2])
    return mean, cov, float(hidden_estimator.log_posterior_from_array(mean))


def _run(sampler, estimator, primary, searches, n_modes=3, **kw):
    mean, cov, _ = primary
    sampler.kwargs["mode_searches"] = searches
    sampler.kwargs["mode_symmetries"] = None
    sampler.kwargs["mode_separation_sigma"] = 1.0
    sampler.kwargs.update(kw)
    return sampler._find_multiple_maps(estimator, n_modes, np.ones(2), mean, cov)


def test_multistart_is_a_valid_mode_search(sampler):
    assert "multistart" in sampler._MODE_SEARCHES


def test_multistart_off_by_default(sampler):
    assert "multistart" not in sampler.kwargs["mode_searches"]


def _found_secondary(modes):
    return any(np.max(np.abs(m[0] - _HiddenBasinLikelihood.B_MU)) < 0.6 for m in modes)


def test_subspace_hypercube_cannot_reach_a_mode_outside_the_subspace(sampler, hidden_estimator, hidden_primary):
    """The failure this search exists to fix, reproduced."""
    modes = _run(
        sampler,
        hidden_estimator,
        hidden_primary,
        ["hypercube"],
        mode_search_subspace=["x"],
        mode_search_nsamples=60,
    )
    assert not _found_secondary(modes), "fixture is not discriminating: the subspace search found it"


def test_multistart_reaches_a_mode_outside_the_subspace(sampler, hidden_estimator, hidden_primary):
    """The fix: full-space starts find what the pinned subspace cannot."""
    modes = _run(
        sampler,
        hidden_estimator,
        hidden_primary,
        ["multistart"],
        mode_search_subspace=["x"],
        mode_multistart_nstarts=40,
    )
    assert _found_secondary(modes), f"secondary not found; modes at {[m[0] for m in modes]}"


def test_multistart_keeps_the_given_primary(sampler, hidden_estimator, hidden_primary):
    """It only adds secondaries -- the primary is passed in, never recomputed."""
    mean, _, logp = hidden_primary
    modes = _run(sampler, hidden_estimator, hidden_primary, ["multistart"], mode_multistart_nstarts=10)
    assert any(np.allclose(m[0], mean) and m[2] == pytest.approx(logp) for m in modes)


def test_multistart_respects_n_modes(sampler, hidden_estimator, hidden_primary):
    modes = _run(sampler, hidden_estimator, hidden_primary, ["multistart"], n_modes=2, mode_multistart_nstarts=25)
    assert len(modes) <= 2


def test_multistart_zero_starts_is_a_no_op(sampler, hidden_estimator, hidden_primary):
    modes = _run(sampler, hidden_estimator, hidden_primary, ["multistart"], mode_multistart_nstarts=0)
    assert len(modes) == 1


def test_multistart_runs_without_the_hypercube_search(sampler, hidden_estimator, hidden_primary, monkeypatch):
    def _boom(*args, **kwargs):
        raise AssertionError("mode_searches=['multistart'] must not run the hypercube search")

    monkeypatch.setattr(sampler, "_latin_hypercube_prior_ranked", _boom, raising=False)
    modes = _run(sampler, hidden_estimator, hidden_primary, ["multistart"], mode_multistart_nstarts=10)
    assert len(modes) >= 1


def test_multistart_composes_with_the_other_searches(sampler, hidden_estimator, hidden_primary):
    """All three are peers: enabling every one must not error or lose the primary."""
    modes = _run(
        sampler,
        hidden_estimator,
        hidden_primary,
        ["hypercube", "multistart", "symmetric"],
        mode_multistart_nstarts=8,
    )
    assert len(modes) >= 1
    assert modes == sorted(modes, key=lambda r: r[2], reverse=True)


# --- Pooled selection ------------------------------------------------------
#
# The searches used to append directly, each stopping at n_modes, so the budget
# was first-come-first-served and the order in `mode_searches` was silently
# decisive. On GW150914 the hypercube search filled every secondary slot with
# near-duplicate azimuth modes and multistart, running second, had all of its
# candidates discarded -- enabling it did nothing, with no error or warning.


def test_a_search_that_fills_the_budget_does_not_starve_the_next(
    sampler, hidden_estimator, hidden_primary, monkeypatch
):
    """The regression, tested at the mechanism rather than via geometry.

    'hypercube' is made to return exactly n_modes junk candidates -- distinct
    enough to survive deduplication, all shallower than the real secondary --
    which is what it did on GW150914 with near-duplicate azimuth modes. Under
    the old append-as-you-go code those filled every slot and multistart's
    candidates were all discarded. Selection on merit must now prefer the
    deeper mode regardless of which search proposed it.
    """
    junk = [
        dict(mean=np.array([3.5, -2.5]), logp=-40.0, source="hypercube"),
        dict(mean=np.array([-4.5, -3.5]), logp=-41.0, source="hypercube"),
    ]
    monkeypatch.setattr(sampler, "_hypercube_candidates", lambda *a, **k: list(junk))

    modes = _run(
        sampler,
        hidden_estimator,
        hidden_primary,
        ["hypercube", "multistart"],
        n_modes=2,
        mode_multistart_nstarts=40,
    )
    assert _found_secondary(modes), (
        "the budget-filling search starved the next one; " f"modes at {[m[0] for m in modes]}"
    )
    assert not any(m[2] < -30 for m in modes), "junk candidates outranked a real mode"


def test_search_order_does_not_change_the_result(sampler, hidden_estimator, hidden_primary):
    """Selection is on merit, so listing the searches either way round agrees."""
    kw = dict(n_modes=3, mode_search_subspace=["x"], mode_search_nsamples=60, mode_multistart_nstarts=40)
    a = _run(sampler, hidden_estimator, hidden_primary, ["hypercube", "multistart"], **kw)
    b = _run(sampler, hidden_estimator, hidden_primary, ["multistart", "hypercube"], **kw)
    assert _found_secondary(a) == _found_secondary(b) is True


def test_selection_keeps_the_best_candidates(sampler, hidden_estimator, hidden_primary):
    """Accepted modes are the highest-log-posterior ones, sorted descending."""
    modes = _run(sampler, hidden_estimator, hidden_primary, ["multistart"], n_modes=3, mode_multistart_nstarts=30)
    logps = [m[2] for m in modes]
    assert logps == sorted(logps, reverse=True)
    assert len(modes) <= 3


def test_symmetry_mirrors_a_candidate_not_only_the_primary(sampler, periodic_estimator, periodic_mode, monkeypatch):
    """Mirrors are proposed against the whole pool, so a symmetry mode can be
    seeded from a candidate another search found rather than only the primary."""
    mean, cov, logp = periodic_mode
    offset = np.array([0.0, 0.9])
    fake = [
        dict(
            mean=mean + offset,
            logp=float(periodic_estimator.log_posterior_from_array(mean + offset)),
            source="multistart",
        )
    ]
    monkeypatch.setattr(sampler, "_multistart_candidates", lambda *a, **k: fake)
    sampler.kwargs["mode_searches"] = ["multistart", "symmetric"]
    sampler.kwargs["mode_symmetries"] = [("phi", np.pi)]
    sampler.kwargs["mode_separation_sigma"] = 0.5
    modes = sampler._find_multiple_maps(periodic_estimator, 4, np.ones(2), mean, cov)
    phis = sorted(round(float(m[0][1]), 3) for m in modes)
    assert len(modes) >= 3, f"expected the candidate and its mirror alongside the primary; got {phis}"
